Meson build files for 1.79
mesonbuild/imgui pull request #8
Opened 2020-11-08 11:58 UTC by stephanlachnit

Closes #7.

First note: with >1.79 the `examples` folder will not include the backend implementations anymore, they will be in the `backends` folder instead.

Second note, regarding #7. I switched from features to booleans, as I don't think that the library should depend on libraries just because they happen to be installed on the system. If one wants a specific implementation, it should be enabled by hand. Kinda important for reproducibility as well, as I want to use this in project that will end up in a Debian package eventually.

Third note, regarding OpenGL. I removed the legacy `opengl2` option, as one can also use OpenGL 2.x with the `opengl3` implementation as well. Also, currently we only have one OpenGL loader, namely `glew`. However, as we can see [here](https://github.com/ocornut/imgui/blob/e5cb04b132cba94f902beb6186cb58b864777012/examples/imgui_impl_opengl3.h#L57-L85), there are much more options. Since `glew` is the preferred option and I don't actually need any of those, I don't really care about implementing the others.

/cc @st4ll1 @XPXPv2 @TommyXR

2020-11-10 16:57 UTC, TommyXR commented
Thank you, that solves a lot of things. Unfortunately I don't have write access to merge, but if it's not merged before the end of the week, I'll add an issue in the [wrapdb repo](https://github.com/mesonbuild/wrapdb/) (as suggested by the wrapdb guidelines).

2020-11-13 20:32 UTC, stephanlachnit commented
@legeana friendly ping

2020-11-20 03:20 UTC, eli-schwartz commented
> Second note, regarding #7. I switched from features to booleans, as I don't think that the library should depend on libraries just because they happen to be installed on the system. If one wants a specific implementation, it should be enabled by hand. Kinda important for reproducibility as well, as I want to use this in project that will end up in a Debian package eventually.

This should be solved by using meson setup --auto-features=disabled and enabling each feature you want by hand. And/or the feature equivalent of `type : 'boolean', value : false` is `type: 'feature', value: 'disabled'` if you want them to not be checked by default. I do NOT see a good reason to change these to booleans.

2020-11-20 03:23 UTC, eli-schwartz commented
You somehow ended up with a file named meson.options instead of meson_options.txt which means:
- the review tool immediately errors due to non-buildsystem files
- meson builddir/ immediately errors with
   ```
   meson.build:14:3: ERROR: Tried to access unknown option "dx9".
   ```

2020-11-20 11:19 UTC, stephanlachnit commented
Oh wow how did I mess that up. Fixed.

2020-11-22 16:52 UTC, eli-schwartz commented
What about my comment w.r.t booleans vs. features defaulting to "disabled"?

2020-11-25 18:00 UTC, eli-schwartz requested changes

2020-11-25 18:00 UTC, eli-schwartz commented on meson.build
> +if get_option('osx').enabled() or (get_option('osx').auto() and target_machine.system() == 'dariwn')
Typo, dariwn vs. darwin

2020-11-25 18:01 UTC, stephanlachnit commented
Switched to features, but I'll still need to test it. Can't test the Windows / OSX stuff, same with marmalade.

2020-11-25 18:09 UTC, stephanlachnit commented
Alright, gave it a test compile and it works. For DirectX I found some Meson examples, so they might even work, for Metal no clue. Marmalade is proprietary, so no chance that I could test it anyway. The other stuff should work, but I didn't try every combination.

2020-12-20 03:12 UTC, eli-schwartz commented
Sorry for forgetting about this. Thanks for the changes.

2020-12-20 03:22 UTC, merged